FROM php:7.4-apache

RUN apt-get update -y \
  && apt-get install -y \
     libmagickwand-dev \
     libfreetype6-dev \
     libjpeg62-turbo-dev \
     libmcrypt-dev \
     libpng-dev \
     libxml2-dev \
     libicu-dev \
     libzip-dev \
     zip \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/* \
  && docker-php-ext-install \
      mcrypt \
      zip \
      bcmath \
      pdo_mysql \
      mysqli \
      mbstring \
      opcache \
      soap \
      imagick \
      zip \
  && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
  && docker-php-ext-install gd \
  && docker-php-ext-configure intl \
  && docker-php-ext-install intl \
  && a2enmod rewrite
